### ISSUE TITLE
can you add rss to your blog?

### ISSUE THREAD

**Issue by maddanio** [ThePhD/ThePhD.github.io#1]
i am not yet hooked on twitter, but i like following via plain old (open) rss, do you think you could provide that on ypur blog :)?

**Comment by maddanio** [comment]
ok, so my rss reader was happy just with the url, still, an rss icon besides the twitter one would be nice, to make it more known, but maybe i am missing common etiquette?

**Comment by ThePhD** [comment]
I can try to add an RSS icon. I'm new to this, so it will take a while to figure out proper.

**Comment by maddanio** [comment]
Ok, cool. Sorry for ranting, great stuff here! I just like to promote free and open channels like rss instead of proprietary ones like fb and twitter

**Comment by maddanio** [comment]
Also: does it work? My reader shows no entries...

**Comment by ThePhD** [comment]
I think it works now: https://thephd.github.io/feed.xml

I don't really use RSS, but it should be good. Thanks for coming around and making the blog better!
